Fix some typos
graeme-a-stewart/python-introduction pull request #2
Opened 2018-10-23 08:06 UTC by daritter

Hi Graeme,

I took the liberty of using your presentation which was very helpful. However there were some typos here and there so I tried to fix them.

2018-10-28 21:03 UTC, graeme-a-stewart requested changes
Great - thanks so much for this. It really helps to have a fresh pair of eyes look over these things.

The only changes I don't want are the ones that are just UK->US spelling variations, where I would like to stick with the UK version.

2018-10-28 21:03 UTC, graeme-a-stewart commented on presentation-insights.ipynb
> +    "Python classes can also inherit from other classes, becoming subclasses - this allows objects which extend or specialize the classes that they inherit from in the usual object oriented way"
This one I don't like - 's' is the standard spelling in UK English, with 'z' used by our American cousins.

2018-10-28 21:03 UTC, graeme-a-stewart commented on presentation-insights.ipynb
> +    "Here's another extremely useful python library, the [*seaborn*](http://seaborn.pydata.org/index.html) statistical visualization library\n",
ditto, keep this as is

2018-10-28 21:03 UTC, graeme-a-stewart commented on presentation-insights.ipynb
> +    "* [scipy](https://www.scipy.org/) - Lots of common scientific routines, such as minimization\n",
ditto

2018-10-28 21:03 UTC, graeme-a-stewart commented on presentation-insights.ipynb
> +    "In case you didn't yet realize it, **Python is pretty amazing**\n",
ditto

2018-10-29 10:15 UTC, daritter commented
Yes, I was assuming there might be some UK/US discussion here :D. I changed all the ones you requested

2018-11-01 14:01 UTC, merged